name: Build and deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install npm packages
      run: npm ci

    - name: Run tests
      run: npm run test:ci

    - name: Build project
      run: npm run build
